import { AI_EDITOR_WORKFLOW_KEY } from '@haohaoxue/samepage-contracts'

export const EDITOR_AI_COMPOSER_MODE = Object.freeze({
  GENERATE: 'generate',
  REWRITE: 'rewrite',
})

export const EDITOR_AI_COMPOSER_STATUS = Object.freeze({
  IDLE: 'idle',
  COMPOSING: 'composing',
  STREAMING: 'streaming',
  READY: 'ready',
  ACCEPTING: 'accepting',
  ACCEPT_SYNC_FAILED: 'accept-sync-failed',
  REJECTING: 'rejecting',
  FAILED: 'failed',
})

export const EDITOR_AI_PREVIEW_STATUS = Object.freeze({
  STREAMING: 'streaming',
  READY: 'ready',
  FAILED: 'failed',
})

export const EDITOR_AI_WORKFLOW_KEY_BY_COMPOSER_MODE = Object.freeze({
  [EDITOR_AI_COMPOSER_MODE.GENERATE]: AI_EDITOR_WORKFLOW_KEY.GENERATE,
  [EDITOR_AI_COMPOSER_MODE.REWRITE]: AI_EDITOR_WORKFLOW_KEY.REWRITE,
})

export const EDITOR_AI_COMPOSER_PLACEHOLDER_BY_MODE = Object.freeze({
  [EDITOR_AI_COMPOSER_MODE.GENERATE]: '描述要生成的正文',
  [EDITOR_AI_COMPOSER_MODE.REWRITE]: '输入改写要求',
})

export const EDITOR_AI_COMPOSER_SUBMIT_LABEL_BY_MODE = Object.freeze({
  [EDITOR_AI_COMPOSER_MODE.GENERATE]: '生成',
  [EDITOR_AI_COMPOSER_MODE.REWRITE]: '改写',
})

export const EDITOR_AI_COMPOSER_SUBMIT_LABEL_BY_STATUS = Object.freeze({
  [EDITOR_AI_COMPOSER_STATUS.IDLE]: null,
  [EDITOR_AI_COMPOSER_STATUS.COMPOSING]: null,
  [EDITOR_AI_COMPOSER_STATUS.STREAMING]: '生成中',
  [EDITOR_AI_COMPOSER_STATUS.READY]: null,
  [EDITOR_AI_COMPOSER_STATUS.ACCEPTING]: '写入中',
  [EDITOR_AI_COMPOSER_STATUS.ACCEPT_SYNC_FAILED]: null,
  [EDITOR_AI_COMPOSER_STATUS.REJECTING]: '拒绝中',
  [EDITOR_AI_COMPOSER_STATUS.FAILED]: null,
})

export const EDITOR_AI_COMPOSER_CLOSE_LABEL_BY_STATUS = Object.freeze({
  [EDITOR_AI_COMPOSER_STATUS.IDLE]: '取消',
  [EDITOR_AI_COMPOSER_STATUS.COMPOSING]: '取消',
  [EDITOR_AI_COMPOSER_STATUS.STREAMING]: '取消',
  [EDITOR_AI_COMPOSER_STATUS.READY]: '拒绝',
  [EDITOR_AI_COMPOSER_STATUS.ACCEPTING]: '处理中',
  [EDITOR_AI_COMPOSER_STATUS.ACCEPT_SYNC_FAILED]: '处理中',
  [EDITOR_AI_COMPOSER_STATUS.REJECTING]: '处理中',
  [EDITOR_AI_COMPOSER_STATUS.FAILED]: '取消',
})

export const EDITOR_AI_COMPOSER_BUSY_BY_STATUS = Object.freeze({
  [EDITOR_AI_COMPOSER_STATUS.IDLE]: false,
  [EDITOR_AI_COMPOSER_STATUS.COMPOSING]: false,
  [EDITOR_AI_COMPOSER_STATUS.STREAMING]: true,
  [EDITOR_AI_COMPOSER_STATUS.READY]: false,
  [EDITOR_AI_COMPOSER_STATUS.ACCEPTING]: true,
  [EDITOR_AI_COMPOSER_STATUS.ACCEPT_SYNC_FAILED]: false,
  [EDITOR_AI_COMPOSER_STATUS.REJECTING]: true,
  [EDITOR_AI_COMPOSER_STATUS.FAILED]: false,
})

export const EDITOR_AI_COMPOSER_SUBMITTABLE_STATUS = EDITOR_AI_COMPOSER_STATUS.COMPOSING
export const EDITOR_AI_COMPOSER_ERROR_FALLBACK = '编辑器 AI 生成失败'
export const EDITOR_AI_ACCEPT_ERROR_FALLBACK = '接收 AI 建议失败'
export const EDITOR_AI_REJECT_ERROR_FALLBACK = '拒绝 AI 建议失败'
export const EDITOR_AI_STALE_ANCHOR_MESSAGE = '正文已变化，请重新发起 AI 操作'
export const EDITOR_AI_GENERATE_TRIGGER_KEY = ' '

export const EDITOR_AI_COMPOSER_WIDTH = 340
export const EDITOR_AI_COMPOSER_ANCHOR_GAP = 8
export const EDITOR_AI_COMPOSER_VIEWPORT_PADDING = 12

export const EDITOR_AI_PREVIEW_PLUGIN_KEY_NAME = 'editorAiPreview'
export const EDITOR_AI_PREVIEW_DECORATION_KEY_PREFIX = 'editor-ai-preview'
export const EDITOR_AI_PREVIEW_CLASS = 'tiptap-ai-preview'
export const EDITOR_AI_PREVIEW_ANCHOR_BLOCK_CLASS = 'tiptap-ai-preview-anchor-block'
export const EDITOR_AI_PREVIEW_SELECTION_CLASS = 'tiptap-ai-preview-selection'

export const EDITOR_AI_PREVIEW_EMPTY_TEXT_BY_STATUS = Object.freeze({
  [EDITOR_AI_PREVIEW_STATUS.STREAMING]: 'AI 正在生成...',
  [EDITOR_AI_PREVIEW_STATUS.READY]: 'AI 正在生成...',
  [EDITOR_AI_PREVIEW_STATUS.FAILED]: 'AI 生成失败',
})

export const EDITOR_AI_STREAM_DONE_PAYLOAD = '[DONE]'

export const EDITOR_AI_STREAM_ERROR_MESSAGE = Object.freeze({
  NO_RESPONSE_BODY: 'no response body',
  INCOMPLETE: 'incomplete editor ai stream',
  INVALID_EVENT: 'invalid editor ai stream event',
})
