export const WORKSPACE_NAME_MAX_LENGTH = 80
export const WORKSPACE_DESCRIPTION_MAX_LENGTH = 200
export const WORKSPACE_ICON_MIME_TYPES = [
  'image/jpeg',
  'image/png',
  'image/webp',
] as const
export const WORKSPACE_ICON_MAX_BYTES = 2 * 1024 * 1024

export const WORKSPACE_TYPE = {
  PERSONAL: 'PERSONAL',
  TEAM: 'TEAM',
} as const

export const WORKSPACE_TYPE_VALUES = [
  WORKSPACE_TYPE.PERSONAL,
  WORKSPACE_TYPE.TEAM,
] as const

export const WORKSPACE_MEMBER_ROLE = {
  OWNER: 'OWNER',
  ADMIN: 'ADMIN',
  MEMBER: 'MEMBER',
} as const

export const WORKSPACE_MEMBER_ROLE_VALUES = [
  WORKSPACE_MEMBER_ROLE.OWNER,
  WORKSPACE_MEMBER_ROLE.ADMIN,
  WORKSPACE_MEMBER_ROLE.MEMBER,
] as const

export const WORKSPACE_MEMBER_STATUS = {
  ACTIVE: 'ACTIVE',
  LEFT: 'LEFT',
  REMOVED: 'REMOVED',
} as const

export const WORKSPACE_MEMBER_STATUS_VALUES = [
  WORKSPACE_MEMBER_STATUS.ACTIVE,
  WORKSPACE_MEMBER_STATUS.LEFT,
  WORKSPACE_MEMBER_STATUS.REMOVED,
] as const

export const WORKSPACE_INVITE_STATUS = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  DECLINED: 'DECLINED',
  CANCELED: 'CANCELED',
} as const

export const WORKSPACE_INVITE_STATUS_VALUES = [
  WORKSPACE_INVITE_STATUS.PENDING,
  WORKSPACE_INVITE_STATUS.ACCEPTED,
  WORKSPACE_INVITE_STATUS.DECLINED,
  WORKSPACE_INVITE_STATUS.CANCELED,
] as const
