import type { SpaceIcon } from '@buddy-shared/spaces/spaceAppearance'
import type { Component } from 'vue'
import {
  Beaker20Filled,
  Beaker20Regular,
  Book20Filled,
  Book20Regular,
  Briefcase20Filled,
  Briefcase20Regular,
  CalendarLtr20Filled,
  CalendarLtr20Regular,
  CodeCircle20Filled,
  CodeCircle20Regular,
  Cube20Filled,
  Cube20Regular,
  Edit20Filled,
  Edit20Regular,
  Folder20Filled,
  Folder20Regular,
  Globe20Filled,
  Globe20Regular,
  Heart20Filled,
  Heart20Regular,
  Home20Filled,
  Home20Regular,
  Image20Filled,
  Image20Regular,
  Lightbulb20Filled,
  Lightbulb20Regular,
  MusicNote220Filled,
  MusicNote220Regular,
  Rocket20Filled,
  Rocket20Regular,
  Shield20Filled,
  Shield20Regular,
  Star20Filled,
  Star20Regular,
  WindowConsole20Filled,
  WindowConsole20Regular,
} from '@vicons/fluent'

export const spaceIconComponents = {
  'folder': Folder20Regular,
  'code': CodeCircle20Regular,
  'book': Book20Regular,
  'pen': Edit20Regular,
  'terminal': WindowConsole20Regular,
  'briefcase': Briefcase20Regular,
  'home': Home20Regular,
  'globe': Globe20Regular,
  'lightbulb': Lightbulb20Regular,
  'rocket': Rocket20Regular,
  'beaker': Beaker20Regular,
  'music': MusicNote220Regular,
  'image': Image20Regular,
  'heart': Heart20Regular,
  'star': Star20Regular,
  'calendar': CalendarLtr20Regular,
  'shield': Shield20Regular,
  'cube': Cube20Regular,
  'folder-filled': Folder20Filled,
  'code-filled': CodeCircle20Filled,
  'book-filled': Book20Filled,
  'pen-filled': Edit20Filled,
  'terminal-filled': WindowConsole20Filled,
  'briefcase-filled': Briefcase20Filled,
  'home-filled': Home20Filled,
  'globe-filled': Globe20Filled,
  'lightbulb-filled': Lightbulb20Filled,
  'rocket-filled': Rocket20Filled,
  'beaker-filled': Beaker20Filled,
  'music-filled': MusicNote220Filled,
  'image-filled': Image20Filled,
  'heart-filled': Heart20Filled,
  'star-filled': Star20Filled,
  'calendar-filled': CalendarLtr20Filled,
  'shield-filled': Shield20Filled,
  'cube-filled': Cube20Filled,
} satisfies Record<SpaceIcon, Component>
