export type {
  CreateCollabTicketResponse,
  CreateDocumentDuplicateOperationResponse,
  CreateDocumentMoveOperationResponse,
  CreateDocumentRequest,
  CreateDocumentResponse,
  CreateDocumentVersionSnapshotRequest,
  CreateDocumentVersionSnapshotResponse,
  DocumentAsset,
  DocumentCurrent,
  DocumentHistory,
  DocumentOperationJob,
  DocumentTrashItem,
  DocumentTreeGroup,
  DocumentVersionSnapshot,
  MoveDocumentTreeOperationRequest,
  PatchDocumentLayoutRequest,
  PatchDocumentMetaRequest,
  PatchDocumentTitleRequest,
  ResolveDocumentAssetsRequest,
  ResolveDocumentAssetsResponse,
  RestoreDocumentVersionSnapshotRequest,
  RestoreDocumentVersionSnapshotResponse,
} from '@haohaoxue/samepage-contracts'
