export const DOCUMENT_COLLECTION = {
  PERSONAL: 'personal',
  COLLABORATION: 'collaboration',
  TEAM: 'team',
} as const

export const DOCUMENT_COLLECTION_VALUES = [
  DOCUMENT_COLLECTION.PERSONAL,
  DOCUMENT_COLLECTION.COLLABORATION,
  DOCUMENT_COLLECTION.TEAM,
] as const

export const DOCUMENT_TREE_COLLECTION_VALUES = [
  DOCUMENT_COLLECTION.PERSONAL,
  DOCUMENT_COLLECTION.COLLABORATION,
  DOCUMENT_COLLECTION.TEAM,
] as const

export const DOCUMENT_OWNED_COLLECTION_VALUES = [
  DOCUMENT_COLLECTION.PERSONAL,
  DOCUMENT_COLLECTION.TEAM,
] as const

export const DOCUMENT_COLLECTION_LABELS = {
  [DOCUMENT_COLLECTION.PERSONAL]: '私有',
  [DOCUMENT_COLLECTION.COLLABORATION]: '协作',
  [DOCUMENT_COLLECTION.TEAM]: '团队',
} as const satisfies Record<(typeof DOCUMENT_COLLECTION_VALUES)[number], string>

export const DOCUMENT_TITLE_MAX_LENGTH = 120
export const DOCUMENT_DEFAULT_TITLE = '新文档'
export const DOCUMENT_CHAT_SEARCH_LIMIT = 20
export const DOCUMENT_CHAT_SEARCH_QUERY_MAX_LENGTH = 80
export const DOCUMENT_IMAGE_MAX_BYTES = 2 * 1024 * 1024

export const DOCUMENT_SAVE_STATE = {
  IDLE: 'idle',
  DIRTY: 'dirty',
  SAVING: 'saving',
  SAVED: 'saved',
  ERROR: 'error',
} as const

export const DOCUMENT_VISIBILITY = {
  PRIVATE: 'PRIVATE',
  WORKSPACE: 'WORKSPACE',
} as const

export const DOCUMENT_VISIBILITY_VALUES = [
  DOCUMENT_VISIBILITY.PRIVATE,
  DOCUMENT_VISIBILITY.WORKSPACE,
] as const

export const DOCUMENT_PAGE_WIDTH_MODE = {
  NARROW: 'NARROW',
  DEFAULT: 'DEFAULT',
  FULL: 'FULL',
} as const

export const DOCUMENT_PAGE_WIDTH_MODE_VALUES = [
  DOCUMENT_PAGE_WIDTH_MODE.NARROW,
  DOCUMENT_PAGE_WIDTH_MODE.DEFAULT,
  DOCUMENT_PAGE_WIDTH_MODE.FULL,
] as const

export const DOCUMENT_PAGE_WIDTH_MODE_LABELS = {
  [DOCUMENT_PAGE_WIDTH_MODE.NARROW]: '较窄',
  [DOCUMENT_PAGE_WIDTH_MODE.DEFAULT]: '默认',
  [DOCUMENT_PAGE_WIDTH_MODE.FULL]: '全宽',
} as const satisfies Record<(typeof DOCUMENT_PAGE_WIDTH_MODE_VALUES)[number], string>

export const DOCUMENT_PANE_STATE = {
  READY: 'ready',
  LOADING: 'loading',
  EMPTY: 'empty',
  UNSELECTED: 'unselected',
  UNSUPPORTED_SCHEMA: 'unsupported-schema',
  NOT_FOUND: 'not-found',
  FORBIDDEN: 'forbidden',
  ERROR: 'error',
} as const

export const DOCUMENT_OPERATION_JOB_TYPE = {
  DUPLICATE_TREE: 'DUPLICATE_TREE',
  MOVE_TREE: 'MOVE_TREE',
} as const

export const DOCUMENT_OPERATION_JOB_TYPE_VALUES = [
  DOCUMENT_OPERATION_JOB_TYPE.DUPLICATE_TREE,
  DOCUMENT_OPERATION_JOB_TYPE.MOVE_TREE,
] as const

export const DOCUMENT_OPERATION_JOB_STATUS = {
  PENDING: 'PENDING',
  RUNNING: 'RUNNING',
  SUCCEEDED: 'SUCCEEDED',
  FAILED: 'FAILED',
} as const

export const DOCUMENT_OPERATION_JOB_STATUS_VALUES = [
  DOCUMENT_OPERATION_JOB_STATUS.PENDING,
  DOCUMENT_OPERATION_JOB_STATUS.RUNNING,
  DOCUMENT_OPERATION_JOB_STATUS.SUCCEEDED,
  DOCUMENT_OPERATION_JOB_STATUS.FAILED,
] as const

export const DOCUMENT_VERSION_SNAPSHOT_SOURCE = {
  INITIAL: 'initial',
  USER: 'user',
  AUTO: 'auto',
  RESTORE: 'restore',
} as const

export const DOCUMENT_VERSION_SNAPSHOT_SOURCE_VALUES = [
  DOCUMENT_VERSION_SNAPSHOT_SOURCE.INITIAL,
  DOCUMENT_VERSION_SNAPSHOT_SOURCE.USER,
  DOCUMENT_VERSION_SNAPSHOT_SOURCE.AUTO,
  DOCUMENT_VERSION_SNAPSHOT_SOURCE.RESTORE,
] as const
