export const COLLAB_RUNTIME_ROLE = {
  EDITOR: 'EDITOR',
} as const

export const COLLAB_RUNTIME_ROLE_VALUES = [COLLAB_RUNTIME_ROLE.EDITOR] as const

export const COLLAB_ERROR_CODE = {
  TICKET_INVALID: 'ticket-invalid',
  TICKET_EXPIRED: 'ticket-expired',
  TICKET_REPLAYED: 'ticket-replayed',
  RATE_LIMITED: 'rate-limited',
  CONNECTION_LIMIT_EXCEEDED: 'connection-limit-exceeded',
  DOCUMENT_MISMATCH: 'document-mismatch',
  ENTRY_MISMATCH: 'entry-mismatch',
  RUNTIME_EPOCH_EXPIRED: 'runtime-epoch-expired',
  PERMISSION_INVALIDATED: 'permission-invalidated',
  READONLY_WRITE_REJECTED: 'readonly-write-rejected',
  UPDATE_TOO_LARGE: 'update-too-large',
  UPDATE_SEQUENCE_GAP: 'update-sequence-gap',
  UPDATE_CHECKPOINTED: 'update-checkpointed',
  CHECKPOINT_EXPIRED: 'checkpoint-expired',
  PERSISTENCE_FAILED: 'persistence-failed',
} as const

export const COLLAB_ERROR_CODE_VALUES = [
  COLLAB_ERROR_CODE.TICKET_INVALID,
  COLLAB_ERROR_CODE.TICKET_EXPIRED,
  COLLAB_ERROR_CODE.TICKET_REPLAYED,
  COLLAB_ERROR_CODE.RATE_LIMITED,
  COLLAB_ERROR_CODE.CONNECTION_LIMIT_EXCEEDED,
  COLLAB_ERROR_CODE.DOCUMENT_MISMATCH,
  COLLAB_ERROR_CODE.ENTRY_MISMATCH,
  COLLAB_ERROR_CODE.RUNTIME_EPOCH_EXPIRED,
  COLLAB_ERROR_CODE.PERMISSION_INVALIDATED,
  COLLAB_ERROR_CODE.READONLY_WRITE_REJECTED,
  COLLAB_ERROR_CODE.UPDATE_TOO_LARGE,
  COLLAB_ERROR_CODE.UPDATE_SEQUENCE_GAP,
  COLLAB_ERROR_CODE.UPDATE_CHECKPOINTED,
  COLLAB_ERROR_CODE.CHECKPOINT_EXPIRED,
  COLLAB_ERROR_CODE.PERSISTENCE_FAILED,
] as const

export const COLLAB_PERMISSION_INVALIDATION_REASON = {
  DOCUMENT_TRASHED: 'document-trashed',
  DOCUMENT_MOVED: 'document-moved',
  COLLABORATION_REVOKED: 'collaboration-revoked',
  MEMBER_REMOVED: 'member-removed',
  RUNTIME_EPOCH_EXPIRED: 'runtime-epoch-expired',
} as const

export const COLLAB_PERMISSION_INVALIDATION_REASON_VALUES = [
  COLLAB_PERMISSION_INVALIDATION_REASON.DOCUMENT_TRASHED,
  COLLAB_PERMISSION_INVALIDATION_REASON.DOCUMENT_MOVED,
  COLLAB_PERMISSION_INVALIDATION_REASON.COLLABORATION_REVOKED,
  COLLAB_PERMISSION_INVALIDATION_REASON.MEMBER_REMOVED,
  COLLAB_PERMISSION_INVALIDATION_REASON.RUNTIME_EPOCH_EXPIRED,
] as const

export const COLLAB_PUBSUB_MESSAGE_TYPE = {
  PERMISSION_INVALIDATION: 'permission-invalidation',
} as const

export const COLLAB_PUBSUB_MESSAGE_TYPE_VALUES = [
  COLLAB_PUBSUB_MESSAGE_TYPE.PERMISSION_INVALIDATION,
] as const

export const COLLAB_REDIS_CHANNEL = {
  PERMISSION_INVALIDATION: 'lexora:collab:permission-invalidation',
} as const

export const DOCUMENT_COLLAB_STATELESS_MESSAGE_TYPE = {
  SAVE_REQUEST: 'document.save.request',
  SAVE_RESULT: 'document.save.result',
} as const

export const DOCUMENT_COLLAB_STATELESS_MESSAGE_TYPE_VALUES = [
  DOCUMENT_COLLAB_STATELESS_MESSAGE_TYPE.SAVE_REQUEST,
  DOCUMENT_COLLAB_STATELESS_MESSAGE_TYPE.SAVE_RESULT,
] as const
