export const TIPTAP_SCHEMA_VERSION = 1 as const
export const TIPTAP_BODY_BLOCK_ID_ATTRIBUTE = 'id' as const

export const TIPTAP_DOCUMENT_COLLABORATION_FIELD = {
  TITLE: 'title',
  BODY: 'body',
} as const

export const TIPTAP_DOCUMENT_COLLABORATION_FIELD_VALUES = [
  TIPTAP_DOCUMENT_COLLABORATION_FIELD.TITLE,
  TIPTAP_DOCUMENT_COLLABORATION_FIELD.BODY,
] as const
