export const CHAT_MESSAGE_STATUS = {
  PENDING: 'pending',
  STREAMING: 'streaming',
  COMPLETED: 'completed',
  FAILED: 'failed',
  CANCELLED: 'cancelled',
} as const

export const CHAT_MESSAGE_STATUS_VALUES = [
  CHAT_MESSAGE_STATUS.PENDING,
  CHAT_MESSAGE_STATUS.STREAMING,
  CHAT_MESSAGE_STATUS.COMPLETED,
  CHAT_MESSAGE_STATUS.FAILED,
  CHAT_MESSAGE_STATUS.CANCELLED,
] as const

export const CHAT_MESSAGE_PART_TYPE = {
  REASONING: 'reasoning',
  TEXT: 'text',
  TOOL_CALL: 'tool_call',
  TOOL_RESULT: 'tool_result',
  SOURCE: 'source',
  CITATION: 'citation',
} as const

export const CHAT_MESSAGE_PART_TYPE_VALUES = [
  CHAT_MESSAGE_PART_TYPE.REASONING,
  CHAT_MESSAGE_PART_TYPE.TEXT,
  CHAT_MESSAGE_PART_TYPE.TOOL_CALL,
  CHAT_MESSAGE_PART_TYPE.TOOL_RESULT,
  CHAT_MESSAGE_PART_TYPE.SOURCE,
  CHAT_MESSAGE_PART_TYPE.CITATION,
] as const

export const CHAT_MESSAGE_FAILURE_REASON = {
  FAILED: 'failed',
  CANCELLED: 'cancelled',
  TIMED_OUT: 'timed_out',
} as const

export const CHAT_MESSAGE_FAILURE_REASON_VALUES = [
  CHAT_MESSAGE_FAILURE_REASON.FAILED,
  CHAT_MESSAGE_FAILURE_REASON.CANCELLED,
  CHAT_MESSAGE_FAILURE_REASON.TIMED_OUT,
] as const

export const CHAT_RUN_STATUS = {
  PENDING: 'pending',
  RUNNING: 'running',
  COMPLETED: 'completed',
  FAILED: 'failed',
  CANCELLED: 'cancelled',
} as const

export const CHAT_RUN_STATUS_VALUES = [
  CHAT_RUN_STATUS.PENDING,
  CHAT_RUN_STATUS.RUNNING,
  CHAT_RUN_STATUS.COMPLETED,
  CHAT_RUN_STATUS.FAILED,
  CHAT_RUN_STATUS.CANCELLED,
] as const

export const CHAT_SESSION_EVENT_TYPE = {
  MESSAGE_CREATED: 'chat.message.created',
  MESSAGE_STATUS_CHANGED: 'chat.message.status.changed',
  MESSAGE_PART_DELTA: 'chat.message.part.delta',
  MESSAGE_COMPLETED: 'chat.message.completed',
  MESSAGE_FAILED: 'chat.message.failed',
  MESSAGE_CANCELLED: 'chat.message.cancelled',
  RUN_STARTED: 'chat.run.started',
  RUN_COMPLETED: 'chat.run.completed',
  RUN_FAILED: 'chat.run.failed',
  RUN_CANCELLED: 'chat.run.cancelled',
  BRANCH_SWITCHED: 'chat.branch.switched',
  TITLE_UPDATED: 'chat.title.updated',
  SNAPSHOT_REQUIRED: 'chat.snapshot.required',
} as const

export const CHAT_SESSION_EVENT_TYPE_VALUES = [
  CHAT_SESSION_EVENT_TYPE.MESSAGE_CREATED,
  CHAT_SESSION_EVENT_TYPE.MESSAGE_STATUS_CHANGED,
  CHAT_SESSION_EVENT_TYPE.MESSAGE_PART_DELTA,
  CHAT_SESSION_EVENT_TYPE.MESSAGE_COMPLETED,
  CHAT_SESSION_EVENT_TYPE.MESSAGE_FAILED,
  CHAT_SESSION_EVENT_TYPE.MESSAGE_CANCELLED,
  CHAT_SESSION_EVENT_TYPE.RUN_STARTED,
  CHAT_SESSION_EVENT_TYPE.RUN_COMPLETED,
  CHAT_SESSION_EVENT_TYPE.RUN_FAILED,
  CHAT_SESSION_EVENT_TYPE.RUN_CANCELLED,
  CHAT_SESSION_EVENT_TYPE.BRANCH_SWITCHED,
  CHAT_SESSION_EVENT_TYPE.TITLE_UPDATED,
  CHAT_SESSION_EVENT_TYPE.SNAPSHOT_REQUIRED,
] as const

export const CHAT_SESSION_DEFAULT_TITLE = '新对话'
export const CHAT_SESSION_TITLE_MAX_LENGTH = 120
export const CHAT_MESSAGE_CONTENT_MAX_LENGTH = 40_000
export const CHAT_MESSAGE_CONTENT_JSON_MAX_LENGTH = 120_000
export const CHAT_MESSAGE_CONTENT_JSON_MAX_NODES = 2_000
export const CHAT_MESSAGE_ATTACHMENT_MAX_COUNT = 20

export const CHAT_SESSION_ORIGIN = {
  GLOBAL: 'global',
  DOCS: 'docs',
} as const

export const CHAT_SESSION_ORIGIN_VALUES = [
  CHAT_SESSION_ORIGIN.GLOBAL,
  CHAT_SESSION_ORIGIN.DOCS,
] as const

export const CHAT_MESSAGE_ATTACHMENT_TYPE = {
  DOCUMENT: 'document',
} as const

export const CHAT_MESSAGE_ATTACHMENT_TYPE_VALUES = [
  CHAT_MESSAGE_ATTACHMENT_TYPE.DOCUMENT,
] as const

export const CHAT_MESSAGE_ATTACHMENT_PLACEMENT = {
  PANEL: 'panel',
  INLINE: 'inline',
} as const

export const CHAT_MESSAGE_ATTACHMENT_PLACEMENT_VALUES = [
  CHAT_MESSAGE_ATTACHMENT_PLACEMENT.PANEL,
  CHAT_MESSAGE_ATTACHMENT_PLACEMENT.INLINE,
] as const
