export const PERMISSIONS = {
  USER_READ_SELF: 'user:read_self',
  USER_UPDATE_SELF: 'user:update_self',
  USER_DELETE_SELF: 'user:delete_self',
  USER_LOOKUP_BY_CODE: 'user:lookup_by_code',
  WORKSPACE_READ_SELF: 'workspace:read_self',
  WORKSPACE_CREATE_SELF: 'workspace:create_self',
  WORKSPACE_UPDATE_SELF: 'workspace:update_self',
  SYSTEM_ADMIN_OVERVIEW_READ: 'system_admin:overview:read',
  SYSTEM_ADMIN_USER_LIST: 'system_admin:user:list',
  SYSTEM_ADMIN_USER_UPDATE_STATUS: 'system_admin:user:update_status',
  SYSTEM_ADMIN_AUTH_GOVERNANCE_READ: 'system_admin:auth_governance:read',
  SYSTEM_ADMIN_AUTH_GOVERNANCE_UPDATE: 'system_admin:auth_governance:update',
  SYSTEM_ADMIN_EMAIL_CONFIG_READ: 'system_admin:email_config:read',
  SYSTEM_ADMIN_EMAIL_CONFIG_UPDATE: 'system_admin:email_config:update',
  SYSTEM_ADMIN_NOTIFICATION_READ: 'system_admin:notification:read',
  SYSTEM_ADMIN_NOTIFICATION_UPDATE: 'system_admin:notification:update',
  SYSTEM_ADMIN_NOTIFICATION_DELETE: 'system_admin:notification:delete',
  SYSTEM_ADMIN_AI_CONFIG_READ: 'system_admin:ai_config:read',
  SYSTEM_ADMIN_AI_CONFIG_UPDATE: 'system_admin:ai_config:update',
  SYSTEM_ADMIN_AUDIT_LOG_LIST: 'system_admin:audit_log:list',
} as const

export const ROLES = {
  USER: 'user',
  SYSTEM_ADMIN: 'system_admin',
} as const

export const PERMISSION_VALUES = [
  PERMISSIONS.USER_READ_SELF,
  PERMISSIONS.USER_UPDATE_SELF,
  PERMISSIONS.USER_DELETE_SELF,
  PERMISSIONS.USER_LOOKUP_BY_CODE,
  PERMISSIONS.WORKSPACE_READ_SELF,
  PERMISSIONS.WORKSPACE_CREATE_SELF,
  PERMISSIONS.WORKSPACE_UPDATE_SELF,
  PERMISSIONS.SYSTEM_ADMIN_OVERVIEW_READ,
  PERMISSIONS.SYSTEM_ADMIN_USER_LIST,
  PERMISSIONS.SYSTEM_ADMIN_USER_UPDATE_STATUS,
  PERMISSIONS.SYSTEM_ADMIN_AUTH_GOVERNANCE_READ,
  PERMISSIONS.SYSTEM_ADMIN_AUTH_GOVERNANCE_UPDATE,
  PERMISSIONS.SYSTEM_ADMIN_EMAIL_CONFIG_READ,
  PERMISSIONS.SYSTEM_ADMIN_EMAIL_CONFIG_UPDATE,
  PERMISSIONS.SYSTEM_ADMIN_NOTIFICATION_READ,
  PERMISSIONS.SYSTEM_ADMIN_NOTIFICATION_UPDATE,
  PERMISSIONS.SYSTEM_ADMIN_NOTIFICATION_DELETE,
  PERMISSIONS.SYSTEM_ADMIN_AI_CONFIG_READ,
  PERMISSIONS.SYSTEM_ADMIN_AI_CONFIG_UPDATE,
  PERMISSIONS.SYSTEM_ADMIN_AUDIT_LOG_LIST,
] as const

export const ROLE_VALUES = [
  ROLES.USER,
  ROLES.SYSTEM_ADMIN,
] as const
