const process = require('node:process')
const { platformResources, resolvePackagingPlatform } = require('../../packaging/buddy/release/platform-definition.mjs')
const { sourceDateEpoch } = require('./buddy.version.json')
const { desktopName, productName: displayName } = require('./package.json')

process.env.SOURCE_DATE_EPOCH ??= String(sourceDateEpoch)

const macro = name => `$${`{${name}}`}`

module.exports = {
  appId: desktopName,
  productName: 'lexora-buddy',
  asar: true,
  asarUnpack: ['node_modules/@anthropic-ai/sandbox-runtime/vendor/**'],
  electronFuses: {
    enableCookieEncryption: true,
    enableNodeCliInspectArguments: false,
    enableNodeOptionsEnvironmentVariable: false,
    onlyLoadAppFromAsar: true,
    runAsNode: false,
  },
  npmRebuild: false,
  directories: {
    output: '.output/package/desktop',
  },
  files: [
    '.output/build/electron/**/*',
    'package.json',
    'resources/icons/app-icon.png',
    '!**/__tests__/**',
  ],
  win: {
    extraResources: platformResources(resolvePackagingPlatform('win32')),
    artifactName: `Lexora-Buddy-${macro('version')}-windows-x64.exe`,
    executableName: displayName,
    icon: 'resources/icons/app-icon.png',
    target: [{ target: 'nsis', arch: ['x64'] }],
  },
  nsis: {
    include: '../../packaging/buddy/windows/installer.nsh',
    oneClick: false,
    allowElevation: false,
    allowToChangeInstallationDirectory: false,
    perMachine: false,
    runAfterFinish: true,
    shortcutName: displayName,
    uninstallDisplayName: displayName,
    deleteAppDataOnUninstall: false,
  },
  linux: {
    extraResources: platformResources(resolvePackagingPlatform('linux')),
    category: 'Utility',
    desktop: {
      entry: {
        Name: displayName,
      },
    },
    executableName: 'lexora-buddy',
    icon: 'resources/icons/app-icon.png',
    synopsis: 'Lexora Buddy local personal AI companion and native desktop pet',
    syncDesktopName: true,
    target: ['deb'],
  },
  deb: {
    appArmorProfile: '../../packaging/buddy/linux/apparmor-profile.tpl',
    packageName: 'lexora-buddy',
    depends: [
      'libcap2',
      'socat',
      'git',
      'libgtk-3-0',
      'libnotify4',
      'libnss3',
      'libxss1',
      'libxtst6',
      'xdg-utils',
      'libatspi2.0-0',
      'libuuid1',
      'libsecret-1-0',
      'libgtk-layer-shell0',
      'webp-pixbuf-loader',
    ],
  },
  pacman: {
    appArmorProfile: '../../packaging/buddy/linux/apparmor-profile.tpl',
    artifactName: `Lexora-Buddy-${macro('version')}-arch-x86_64.pkg.tar.zst`,
    compression: 'zstd',
    packageName: 'lexora-buddy',
    depends: [
      'alsa-lib',
      'at-spi2-core',
      'cairo',
      'dbus',
      'desktop-file-utils',
      'expat',
      'gcc-libs',
      'glib2',
      'glibc',
      'git',
      'gtk-layer-shell',
      'gtk3',
      'hicolor-icon-theme',
      'libcups',
      'libcap',
      'libnotify',
      'libsecret',
      'libx11',
      'libxcb',
      'libxcomposite',
      'libxdamage',
      'libxext',
      'libxfixes',
      'libxkbcommon',
      'libxrandr',
      'libxss',
      'libxtst',
      'mesa',
      'nspr',
      'nss',
      'pango',
      'socat',
      'systemd-libs',
      'util-linux-libs',
      'xdg-utils',
    ],
  },
  artifactName: `Lexora-Buddy-${macro('version')}-${macro('os')}-${macro('arch')}.${macro('ext')}`,
}
