export type {
  CreatePlatformNotificationRequest,
  DocumentCollaborationUserInviteNotification,
  GetPlatformNotificationsQuery,
  NotificationItem,
  NotificationListFilter,
  NotificationListQuery,
  NotificationListResponse,
  NotificationMarkAllReadResponse,
  NotificationSummary,
  PlatformNotification,
  PlatformNotificationListResponse,
  PlatformNotificationStatus,
  UpdatePlatformNotificationRequest,
} from '@haohaoxue/samepage-contracts'
