export const DOCUMENT_SINGLE_PUBLICATION_STATE = {
  INHERIT: 'INHERIT',
  ENABLED: 'ENABLED',
  DISABLED: 'DISABLED',
} as const

export const DOCUMENT_SINGLE_PUBLICATION_STATE_VALUES = [
  DOCUMENT_SINGLE_PUBLICATION_STATE.INHERIT,
  DOCUMENT_SINGLE_PUBLICATION_STATE.ENABLED,
  DOCUMENT_SINGLE_PUBLICATION_STATE.DISABLED,
] as const

export const DOCUMENT_SINGLE_PUBLICATION_EFFECTIVE_STATE = {
  ENABLED: 'ENABLED',
  INHERITED_ENABLED: 'INHERITED_ENABLED',
  DISABLED: 'DISABLED',
  UNPUBLISHED: 'UNPUBLISHED',
} as const

export const DOCUMENT_SINGLE_PUBLICATION_EFFECTIVE_STATE_VALUES = [
  DOCUMENT_SINGLE_PUBLICATION_EFFECTIVE_STATE.ENABLED,
  DOCUMENT_SINGLE_PUBLICATION_EFFECTIVE_STATE.INHERITED_ENABLED,
  DOCUMENT_SINGLE_PUBLICATION_EFFECTIVE_STATE.DISABLED,
  DOCUMENT_SINGLE_PUBLICATION_EFFECTIVE_STATE.UNPUBLISHED,
] as const

export const DOCUMENT_SINGLE_PUBLICATION_EFFECTIVE_STATE_LABELS = {
  [DOCUMENT_SINGLE_PUBLICATION_EFFECTIVE_STATE.ENABLED]: '公开',
  [DOCUMENT_SINGLE_PUBLICATION_EFFECTIVE_STATE.INHERITED_ENABLED]: '继承公开',
  [DOCUMENT_SINGLE_PUBLICATION_EFFECTIVE_STATE.DISABLED]: '已关闭',
  [DOCUMENT_SINGLE_PUBLICATION_EFFECTIVE_STATE.UNPUBLISHED]: '未公开',
} as const satisfies Record<(typeof DOCUMENT_SINGLE_PUBLICATION_EFFECTIVE_STATE_VALUES)[number], string>

export const DOCUMENT_PUBLICATION_SITE_STATUS = {
  ACTIVE: 'ACTIVE',
  DISABLED: 'DISABLED',
  REMOVED: 'REMOVED',
} as const

export const DOCUMENT_PUBLICATION_SITE_STATUS_VALUES = [
  DOCUMENT_PUBLICATION_SITE_STATUS.ACTIVE,
  DOCUMENT_PUBLICATION_SITE_STATUS.DISABLED,
  DOCUMENT_PUBLICATION_SITE_STATUS.REMOVED,
] as const

export const DOCUMENT_PUBLICATION_ENTRY_STATUS = {
  ACTIVE: 'ACTIVE',
  HIDDEN: 'HIDDEN',
  REMOVED: 'REMOVED',
} as const

export const DOCUMENT_PUBLICATION_ENTRY_STATUS_VALUES = [
  DOCUMENT_PUBLICATION_ENTRY_STATUS.ACTIVE,
  DOCUMENT_PUBLICATION_ENTRY_STATUS.HIDDEN,
  DOCUMENT_PUBLICATION_ENTRY_STATUS.REMOVED,
] as const

export const DOCUMENT_PUBLICATION_SITE_THEME = {
  DEFAULT: 'DEFAULT',
} as const

export const DOCUMENT_PUBLICATION_SITE_THEME_VALUES = [
  DOCUMENT_PUBLICATION_SITE_THEME.DEFAULT,
] as const

export const DOCUMENT_PUBLICATION_SITE_HOME_MODE = {
  LANDING: 'LANDING',
  DOCUMENT: 'DOCUMENT',
} as const

export const DOCUMENT_PUBLICATION_SITE_HOME_MODE_VALUES = [
  DOCUMENT_PUBLICATION_SITE_HOME_MODE.LANDING,
  DOCUMENT_PUBLICATION_SITE_HOME_MODE.DOCUMENT,
] as const

export const DOCUMENT_SITE_PUBLICATION_PAGE_SCOPE = {
  PAGE: 'PAGE',
  DESCENDANTS: 'DESCENDANTS',
} as const

export const DOCUMENT_SITE_PUBLICATION_PAGE_SCOPE_VALUES = [
  DOCUMENT_SITE_PUBLICATION_PAGE_SCOPE.PAGE,
  DOCUMENT_SITE_PUBLICATION_PAGE_SCOPE.DESCENDANTS,
] as const

export const DOCUMENT_SITE_PUBLICATION_PAGE_SCOPE_LABELS = {
  [DOCUMENT_SITE_PUBLICATION_PAGE_SCOPE.PAGE]: '仅当前页面',
  [DOCUMENT_SITE_PUBLICATION_PAGE_SCOPE.DESCENDANTS]: '当前页面及子页面',
} as const satisfies Record<(typeof DOCUMENT_SITE_PUBLICATION_PAGE_SCOPE_VALUES)[number], string>

export const DOCUMENT_SINGLE_PUBLICATION_SCOPE = {
  PAGE: DOCUMENT_SITE_PUBLICATION_PAGE_SCOPE.PAGE,
  DESCENDANTS: DOCUMENT_SITE_PUBLICATION_PAGE_SCOPE.DESCENDANTS,
} as const

export const DOCUMENT_SINGLE_PUBLICATION_SCOPE_VALUES = [
  DOCUMENT_SINGLE_PUBLICATION_SCOPE.PAGE,
  DOCUMENT_SINGLE_PUBLICATION_SCOPE.DESCENDANTS,
] as const

export const DOCUMENT_SINGLE_PUBLICATION_SCOPE_LABELS = {
  [DOCUMENT_SINGLE_PUBLICATION_SCOPE.PAGE]: '仅当前页面',
  [DOCUMENT_SINGLE_PUBLICATION_SCOPE.DESCENDANTS]: '当前页面及子页面',
} as const satisfies Record<(typeof DOCUMENT_SINGLE_PUBLICATION_SCOPE_VALUES)[number], string>

export const DOCUMENT_PUBLICATION_NAV_ITEM_TYPE = {
  INTERNAL: 'INTERNAL',
  EXTERNAL: 'EXTERNAL',
} as const

export const DOCUMENT_PUBLICATION_NAV_ITEM_TYPE_VALUES = [
  DOCUMENT_PUBLICATION_NAV_ITEM_TYPE.INTERNAL,
  DOCUMENT_PUBLICATION_NAV_ITEM_TYPE.EXTERNAL,
] as const

export const DOCUMENT_PUBLICATION_NAV_ITEM_INTERNAL_TARGET = {
  HOME: 'HOME',
  SECTION: 'SECTION',
  PAGE: 'PAGE',
} as const

export const DOCUMENT_PUBLICATION_NAV_ITEM_INTERNAL_TARGET_VALUES = [
  DOCUMENT_PUBLICATION_NAV_ITEM_INTERNAL_TARGET.HOME,
  DOCUMENT_PUBLICATION_NAV_ITEM_INTERNAL_TARGET.SECTION,
  DOCUMENT_PUBLICATION_NAV_ITEM_INTERNAL_TARGET.PAGE,
] as const

export const DOCUMENT_PUBLICATION_NAV_ITEM_EXTERNAL_TARGET = {
  SELF: 'SELF',
  BLANK: 'BLANK',
} as const

export const DOCUMENT_PUBLICATION_NAV_ITEM_EXTERNAL_TARGET_VALUES = [
  DOCUMENT_PUBLICATION_NAV_ITEM_EXTERNAL_TARGET.SELF,
  DOCUMENT_PUBLICATION_NAV_ITEM_EXTERNAL_TARGET.BLANK,
] as const

export const DOCUMENT_SINGLE_PUBLICATION_ROUTE_PREFIX = '/p'
export const DOCUMENT_SITE_PUBLICATION_ROUTE_PREFIX = '/s'
export const DOCUMENT_PUBLICATION_SITE_TITLE_MAX_LENGTH = 30
export const DOCUMENT_PUBLICATION_SITE_HOME_NAME_MAX_LENGTH = 30
export const DOCUMENT_PUBLICATION_SITE_HOME_TEXT_MAX_LENGTH = 60
export const DOCUMENT_PUBLICATION_SITE_HOME_TAGLINE_MAX_LENGTH = 60
export const DOCUMENT_PUBLICATION_SITE_FOOTER_MESSAGE_MAX_LENGTH = 50
export const DOCUMENT_PUBLICATION_SITE_FOOTER_COPYRIGHT_MAX_LENGTH = 30

export const DOCUMENT_PUBLICATION_SITE_MEDIA_KIND = {
  LOGO: 'logo',
  HOME_LOGO: 'home-logo',
} as const

export const DOCUMENT_PUBLICATION_SITE_MEDIA_KIND_VALUES = [
  DOCUMENT_PUBLICATION_SITE_MEDIA_KIND.LOGO,
  DOCUMENT_PUBLICATION_SITE_MEDIA_KIND.HOME_LOGO,
] as const

export const DOCUMENT_PUBLICATION_SITE_MEDIA_MIME_TYPES = [
  'image/jpeg',
  'image/png',
  'image/webp',
  'image/svg+xml',
] as const

export const DOCUMENT_PUBLICATION_SITE_LOGO_MEDIA_MAX_BYTES = 512 * 1024
export const DOCUMENT_PUBLICATION_SITE_HOME_LOGO_MEDIA_MAX_BYTES = 2 * 1024 * 1024
export const DOCUMENT_PUBLICATION_SITE_MEDIA_MAX_BYTES_BY_KIND = {
  [DOCUMENT_PUBLICATION_SITE_MEDIA_KIND.LOGO]: DOCUMENT_PUBLICATION_SITE_LOGO_MEDIA_MAX_BYTES,
  [DOCUMENT_PUBLICATION_SITE_MEDIA_KIND.HOME_LOGO]: DOCUMENT_PUBLICATION_SITE_HOME_LOGO_MEDIA_MAX_BYTES,
} as const satisfies Record<(typeof DOCUMENT_PUBLICATION_SITE_MEDIA_KIND_VALUES)[number], number>

export const DOCUMENT_PUBLICATION_DEFAULT_SITE_HOME_CONFIG = {
  hero: {
    name: 'SamePage',
    text: 'AI 与协作',
    tagline: null,
    imageUrl: null,
  },
  actions: [],
  features: [],
  footer: {
    message: null,
    copyright: null,
  },
} as const
