export const DOCUMENT_COLLABORATION_PERMISSION = {
  READ: 'READ',
  EDIT: 'EDIT',
} as const

export const DOCUMENT_COLLABORATION_PERMISSION_VALUES = [
  DOCUMENT_COLLABORATION_PERMISSION.READ,
  DOCUMENT_COLLABORATION_PERMISSION.EDIT,
] as const

export const DOCUMENT_COLLABORATION_PERMISSION_LABELS = {
  [DOCUMENT_COLLABORATION_PERMISSION.READ]: '可阅读',
  [DOCUMENT_COLLABORATION_PERMISSION.EDIT]: '可编辑',
} as const satisfies Record<(typeof DOCUMENT_COLLABORATION_PERMISSION_VALUES)[number], string>

export const DOCUMENT_COLLABORATION_SCOPE = {
  SELF: 'SELF',
  DESCENDANTS: 'DESCENDANTS',
} as const

export const DOCUMENT_COLLABORATION_SCOPE_VALUES = [
  DOCUMENT_COLLABORATION_SCOPE.SELF,
  DOCUMENT_COLLABORATION_SCOPE.DESCENDANTS,
] as const

export const DOCUMENT_COLLABORATION_SCOPE_LABELS = {
  [DOCUMENT_COLLABORATION_SCOPE.SELF]: '仅当前页面',
  [DOCUMENT_COLLABORATION_SCOPE.DESCENDANTS]: '当前页面及子页面',
} as const satisfies Record<(typeof DOCUMENT_COLLABORATION_SCOPE_VALUES)[number], string>

export const DOCUMENT_COLLABORATION_GRANT_SOURCE_TYPE = {
  USER_INVITE: 'USER_INVITE',
  LINK_INVITE: 'LINK_INVITE',
  MANUAL: 'MANUAL',
} as const

export const DOCUMENT_COLLABORATION_GRANT_SOURCE_TYPE_VALUES = [
  DOCUMENT_COLLABORATION_GRANT_SOURCE_TYPE.USER_INVITE,
  DOCUMENT_COLLABORATION_GRANT_SOURCE_TYPE.LINK_INVITE,
  DOCUMENT_COLLABORATION_GRANT_SOURCE_TYPE.MANUAL,
] as const

export const DOCUMENT_COLLABORATION_GRANT_SOURCE_TYPE_LABELS = {
  [DOCUMENT_COLLABORATION_GRANT_SOURCE_TYPE.USER_INVITE]: '指定用户邀请',
  [DOCUMENT_COLLABORATION_GRANT_SOURCE_TYPE.LINK_INVITE]: '链接邀请',
  [DOCUMENT_COLLABORATION_GRANT_SOURCE_TYPE.MANUAL]: '手动授权',
} as const satisfies Record<(typeof DOCUMENT_COLLABORATION_GRANT_SOURCE_TYPE_VALUES)[number], string>

export const DOCUMENT_COLLABORATION_GRANT_STATUS = {
  ACTIVE: 'ACTIVE',
  REMOVED: 'REMOVED',
} as const

export const DOCUMENT_COLLABORATION_GRANT_STATUS_VALUES = [
  DOCUMENT_COLLABORATION_GRANT_STATUS.ACTIVE,
  DOCUMENT_COLLABORATION_GRANT_STATUS.REMOVED,
] as const

export const DOCUMENT_COLLABORATION_USER_INVITE_STATUS = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  DECLINED: 'DECLINED',
  CANCELED: 'CANCELED',
} as const

export const DOCUMENT_COLLABORATION_USER_INVITE_STATUS_VALUES = [
  DOCUMENT_COLLABORATION_USER_INVITE_STATUS.PENDING,
  DOCUMENT_COLLABORATION_USER_INVITE_STATUS.ACCEPTED,
  DOCUMENT_COLLABORATION_USER_INVITE_STATUS.DECLINED,
  DOCUMENT_COLLABORATION_USER_INVITE_STATUS.CANCELED,
] as const

export const DOCUMENT_COLLABORATION_ACCESS_SOURCE = {
  OWNER: 'OWNER',
  WORKSPACE: 'WORKSPACE',
  GRANT: 'GRANT',
} as const

export const DOCUMENT_COLLABORATION_ACCESS_SOURCE_VALUES = [
  DOCUMENT_COLLABORATION_ACCESS_SOURCE.OWNER,
  DOCUMENT_COLLABORATION_ACCESS_SOURCE.WORKSPACE,
  DOCUMENT_COLLABORATION_ACCESS_SOURCE.GRANT,
] as const

export const DOCUMENT_COLLABORATION_COLLABORATOR_SOURCE = {
  DIRECT: 'DIRECT',
  INHERITED: 'INHERITED',
} as const

export const DOCUMENT_COLLABORATION_COLLABORATOR_SOURCE_VALUES = [
  DOCUMENT_COLLABORATION_COLLABORATOR_SOURCE.DIRECT,
  DOCUMENT_COLLABORATION_COLLABORATOR_SOURCE.INHERITED,
] as const

export const COLLABORATION_RESOLVER_ENTRY_TYPE = {
  DOCUMENT_USER_INVITE: 'DOCUMENT_USER_INVITE',
  DOCUMENT_LINK_INVITE: 'DOCUMENT_LINK_INVITE',
} as const

export const COLLABORATION_RESOLVER_ENTRY_TYPE_VALUES = [
  COLLABORATION_RESOLVER_ENTRY_TYPE.DOCUMENT_USER_INVITE,
  COLLABORATION_RESOLVER_ENTRY_TYPE.DOCUMENT_LINK_INVITE,
] as const

export const COLLABORATION_RESOLVER_ENTRY_STATUS = {
  ACTIVE: 'ACTIVE',
  REVOKED: 'REVOKED',
} as const

export const COLLABORATION_RESOLVER_ENTRY_STATUS_VALUES = [
  COLLABORATION_RESOLVER_ENTRY_STATUS.ACTIVE,
  COLLABORATION_RESOLVER_ENTRY_STATUS.REVOKED,
] as const

export const DOCUMENT_COLLABORATION_RESOLVER_STATUS = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  DECLINED: 'DECLINED',
  CANCELED: 'CANCELED',
  ENABLED: 'ENABLED',
  DISABLED: 'DISABLED',
} as const

export const DOCUMENT_COLLABORATION_RESOLVER_STATUS_VALUES = [
  DOCUMENT_COLLABORATION_RESOLVER_STATUS.PENDING,
  DOCUMENT_COLLABORATION_RESOLVER_STATUS.ACCEPTED,
  DOCUMENT_COLLABORATION_RESOLVER_STATUS.DECLINED,
  DOCUMENT_COLLABORATION_RESOLVER_STATUS.CANCELED,
  DOCUMENT_COLLABORATION_RESOLVER_STATUS.ENABLED,
  DOCUMENT_COLLABORATION_RESOLVER_STATUS.DISABLED,
] as const

export const DOCUMENT_COLLABORATION_LINK_INVITE_STATE = {
  NONE: 'NONE',
  ENABLED: 'ENABLED',
  DISABLED: 'DISABLED',
} as const

export const DOCUMENT_COLLABORATION_LINK_INVITE_STATE_VALUES = [
  DOCUMENT_COLLABORATION_LINK_INVITE_STATE.NONE,
  DOCUMENT_COLLABORATION_LINK_INVITE_STATE.ENABLED,
  DOCUMENT_COLLABORATION_LINK_INVITE_STATE.DISABLED,
] as const

export const DOCUMENT_COLLABORATION_LINK_INVITE_STATE_LABELS = {
  [DOCUMENT_COLLABORATION_LINK_INVITE_STATE.NONE]: '未开启',
  [DOCUMENT_COLLABORATION_LINK_INVITE_STATE.ENABLED]: '已开启',
  [DOCUMENT_COLLABORATION_LINK_INVITE_STATE.DISABLED]: '已关闭',
} as const satisfies Record<(typeof DOCUMENT_COLLABORATION_LINK_INVITE_STATE_VALUES)[number], string>

export const DOCUMENT_COLLABORATION_RANGE_SUMMARY = {
  NONE: 'NONE',
  SELF: 'SELF',
  DESCENDANTS: 'DESCENDANTS',
  MIXED: 'MIXED',
} as const

export const DOCUMENT_COLLABORATION_RANGE_SUMMARY_VALUES = [
  DOCUMENT_COLLABORATION_RANGE_SUMMARY.NONE,
  DOCUMENT_COLLABORATION_RANGE_SUMMARY.SELF,
  DOCUMENT_COLLABORATION_RANGE_SUMMARY.DESCENDANTS,
  DOCUMENT_COLLABORATION_RANGE_SUMMARY.MIXED,
] as const

export const DOCUMENT_COLLABORATION_RANGE_SUMMARY_LABELS = {
  [DOCUMENT_COLLABORATION_RANGE_SUMMARY.NONE]: '未配置',
  [DOCUMENT_COLLABORATION_RANGE_SUMMARY.SELF]: '仅当前页面',
  [DOCUMENT_COLLABORATION_RANGE_SUMMARY.DESCENDANTS]: '含子页面',
  [DOCUMENT_COLLABORATION_RANGE_SUMMARY.MIXED]: '混合',
} as const satisfies Record<(typeof DOCUMENT_COLLABORATION_RANGE_SUMMARY_VALUES)[number], string>

export const DOCUMENT_COLLABORATION_LINK_PASSWORD_LENGTH = 6
export const DOCUMENT_COLLABORATION_LINK_PASSWORD_REGEX = /^\d{6}$/
